//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPINI_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHOPINI_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить строку.
        /// </summary>
        public static string add_new {
            get {
                return ResourceManager.GetString("add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить изменения.
        /// </summary>
        public static string apply_change {
            get {
                return ResourceManager.GetString("apply_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить все данные?.
        /// </summary>
        public static string clear_all_data {
            get {
                return ResourceManager.GetString("clear_all_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать SHOPINI.
        /// </summary>
        public static string create_shop {
            get {
                return ResourceManager.GetString("create_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создаст папку SHOPINI_ENG рядом с сохраняемым файлом, в котором сохранится копия SHOPINI файла, отличающаяся названием магазина/коробки.
        /// </summary>
        public static string eng_version_mark {
            get {
                return ResourceManager.GetString("eng_version_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        public static string help_menuitem {
            get {
                return ResourceManager.GetString("help_menuitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа предназначена для редактирования SHOPINI файлов. Обязательно поместите ITEMINFO рядом с программой. Поля набора класснеймов и названий предметов работают как поиск, в выпадающем списке появляются варианты. Управление:.
        /// </summary>
        public static string help_text_1 {
            get {
                return ResourceManager.GetString("help_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ENTER - при активных строках &quot;предмет&quot;, &quot;уровень&quot;, &quot;цена&quot; внизу добавляет строку при типе магазина 1, при 0 и 2 предлагает заменить существующую новыми данными, если указанный предмет уже имеется, если нет - добавляет строку.
        /// </summary>
        public static string help_text_2 {
            get {
                return ResourceManager.GetString("help_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE - удаляет выбранные строки (одну или несколько).
        /// </summary>
        public static string help_text_3 {
            get {
                return ResourceManager.GetString("help_text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При выборе нескольких строк есть возможность редактирования одного или нескольких параметров. Для этого нужно изменить нужные параметры и принять изменения..
        /// </summary>
        public static string help_text_5 {
            get {
                return ResourceManager.GetString("help_text_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Присутствует возможность сохранения одновременно на двух языках. Для этого отметьте соответствующий пункт рядом с названием магазина/коробки. Второй файл будет сохранён в папке SHOPINI_ENG, созданной в директории сохраняемого файла..
        /// </summary>
        public static string help_text_6 {
            get {
                return ResourceManager.GetString("help_text_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По каким-нибудь вопросам можно в vk.com/abb_228 (https://vk.com/id271343327), racdenis@yandex.ru, Discord: abb_228, Steam: racdenis_.
        /// </summary>
        public static string help_text_7 {
            get {
                return ResourceManager.GetString("help_text_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование предмета.
        /// </summary>
        public static string item_edit_form {
            get {
                return ResourceManager.GetString("item_edit_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предмет.
        /// </summary>
        public static string item_text {
            get {
                return ResourceManager.GetString("item_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ITEMINFO не найден!.
        /// </summary>
        public static string iteminfo_not_ok {
            get {
                return ResourceManager.GetString("iteminfo_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ITEMINFO обнаружен..
        /// </summary>
        public static string iteminfo_ok {
            get {
                return ResourceManager.GetString("iteminfo_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указать ITEMINFO....
        /// </summary>
        public static string iteminfo_set {
            get {
                return ResourceManager.GetString("iteminfo_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        public static string level_text {
            get {
                return ResourceManager.GetString("level_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ещё один редактор SHOPINI.
        /// </summary>
        public static string main_form {
            get {
                return ResourceManager.GetString("main_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Массовое редактирование.
        /// </summary>
        public static string mass_edit {
            get {
                return ResourceManager.GetString("mass_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь до ITEMINFO....
        /// </summary>
        public static string open_iteminfo {
            get {
                return ResourceManager.GetString("open_iteminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть SHOPINI.
        /// </summary>
        public static string open_shop {
            get {
                return ResourceManager.GetString("open_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string price_text {
            get {
                return ResourceManager.GetString("price_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PriceCoeff.
        /// </summary>
        public static string pricecoeff_text {
            get {
                return ResourceManager.GetString("pricecoeff_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл уже существует. Заменить?.
        /// </summary>
        public static string replace_file_ask {
            get {
                return ResourceManager.GetString("replace_file_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить уже существующую строку?.
        /// </summary>
        public static string replace_string_or_not {
            get {
                return ResourceManager.GetString("replace_string_or_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить SHOPINI.
        /// </summary>
        public static string save_shop {
            get {
                return ResourceManager.GetString("save_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить SHOPINI как.
        /// </summary>
        public static string save_shop_as {
            get {
                return ResourceManager.GetString("save_shop_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название (англ).
        /// </summary>
        public static string shopname_text_en {
            get {
                return ResourceManager.GetString("shopname_text_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string shopname_text_ru {
            get {
                return ResourceManager.GetString("shopname_text_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string type_text {
            get {
                return ResourceManager.GetString("type_text", resourceCulture);
            }
        }
    }
}
